# Generated by Django 5.1.6 on 2025-02-16 21:05

import preventixapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
