# Generated by Django 5.1.6 on 2025-02-16 21:50

import preventixapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventixapp', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=255, validators=[preventixapp.models.validate_address]),
        ),
    ]
