# Generated by Django 5.1.6 on 2025-03-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventixapp', '0005_alter_medicalfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='MedicalFile',
        ),
    ]
