# Generated by Django 5.2 on 2025-05-13 03:11

import preventixapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventixapp', '0006_delete_appointment_delete_medicalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(default='sin direccion', max_length=50, validators=[preventixapp.models.validate_address]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, verbose_name='EPS / Aseguradora'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1111111111, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
