# Generated by Django 5.2 on 2025-05-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventixapp', '0007_customuser_blood_type_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
