# Generated by Django 5.2 on 2025-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventixapp', '0010_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
