# Generated by Django 5.1.6 on 2025-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('pills_per_dose', models.PositiveIntegerField()),
                ('dosage_mg', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_hours', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('administration_method', models.CharField(choices=[('Oral', 'Oral'), ('Inyección', 'Inyección'), ('Tópico', 'Tópico'), ('Inhalado', 'Inhalado'), ('Otro', 'Otro')], default='Oral', max_length=20)),
                ('restrictions', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
