# Generated by Django 5.1.6 on 2025-04-24 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0003_medicalfile_user_prescription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_mg',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pills_per_dose',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_amount',
            field=models.FloatField(blank=True, help_text='Dosis numérica (ej: 500 mg, si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_unit',
            field=models.CharField(blank=True, help_text='Unidad de dosis (ej: mg, ml)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='unit_per_dose',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad por dosis (ej: 2 pastillas, 5 ml)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Duración del tratamiento en días'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='interval_hours',
            field=models.PositiveIntegerField(help_text='Frecuencia en horas entre dosis (ej: cada 8 horas)'),
        ),
    ]
